# This workflow will build and push a new container image to ACR and deploy ACI

name: Dev Build and Deployment

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI: ""

permissions:
  packages: write
  contents: read
  
defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build the App
      run: |
          npm install
          npm run build

  build-and-push:
    name: Build Image & Push to Docker Hub
    runs-on: ubuntu-latest
   # needs: 
    # - test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: nagababu152/github-demo:latest
